#!/usr/bin/env python3
"""
Generate a .env for the Homebrewing Assistant stack.

Produces strong, fresh secrets — including a new Supabase JWT_SECRET and matching
signed ANON_KEY / SERVICE_ROLE_KEY (HS256, no external deps) — so the stack does
NOT ship the well-known demo keys. Local-first single-user setup (architecture D10).

Usage:
    python3 scripts/gen-env.py > .env        # write real secrets
    python3 scripts/gen-env.py --print       # preview to stdout

Re-running mints NEW secrets. Do it once, before first `docker compose up`.
Regenerating after the DB volume exists will orphan the old Postgres password.
"""
import base64, hashlib, hmac, json, secrets, string, sys, time

ALNUM = string.ascii_letters + string.digits


def rand(n: int, alphabet: str = ALNUM) -> str:
    return "".join(secrets.choice(alphabet) for _ in range(n))


def b64url(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).rstrip(b"=").decode()


def sign_jwt(role: str, secret: str, iat: int, exp: int) -> str:
    header = {"alg": "HS256", "typ": "JWT"}
    payload = {"role": role, "iss": "supabase", "iat": iat, "exp": exp}
    segs = [
        b64url(json.dumps(header, separators=(",", ":")).encode()),
        b64url(json.dumps(payload, separators=(",", ":")).encode()),
    ]
    signing_input = ".".join(segs).encode()
    sig = hmac.new(secret.encode(), signing_input, hashlib.sha256).digest()
    return ".".join(segs + [b64url(sig)])


def main() -> None:
    now = int(time.time())
    exp = now + 10 * 365 * 24 * 3600  # ~10 years

    jwt_secret = rand(48)
    anon_key = sign_jwt("anon", jwt_secret, now, exp)
    service_key = sign_jwt("service_role", jwt_secret, now, exp)

    # URL/psql-safe passwords (used inside postgres:// URLs by Supabase services)
    postgres_password = rand(32)
    dashboard_password = rand(24)
    agent_db_password = rand(32)
    mem_writer_db_password = rand(32)

    env = f"""# =============================================================================
# Homebrewing Assistant — environment  (GENERATED by scripts/gen-env.py)
# Local-first, single-user. Do NOT commit this file (see .gitignore).
# =============================================================================

# --- n8n metadata Postgres (workflow definitions only) -----------------------
N8N_POSTGRES_USER=root
N8N_POSTGRES_PASSWORD={rand(32)}
N8N_POSTGRES_DB=n8n

# --- n8n app secrets ---------------------------------------------------------
N8N_ENCRYPTION_KEY={secrets.token_hex(24)}
N8N_USER_MANAGEMENT_JWT_SECRET={secrets.token_hex(24)}
N8N_DEFAULT_BINARY_DATA_MODE=filesystem

# --- Ollama / models (architecture §4) --------------------------------------
# Verify these tags exist on ollama.com/library before first pull (§4.3).
OLLAMA_CHAT_MODEL=gemma4:12b
OLLAMA_EMBED_MODEL=bge-m3
OLLAMA_HOST=ollama:11434

# --- image serving (architecture §3.8) --------------------------------------
IMAGE_BASE_URL=http://localhost:8080

# --- app DB roles the n8n agent uses (architecture §8.4) --------------------
# n8n_agent  : read-only, nlq surface only
# mem_writer : EXECUTE on mem.f_save_memory only
AGENT_DB_PASSWORD={agent_db_password}
MEM_WRITER_DB_PASSWORD={mem_writer_db_password}

# =============================================================================
# Supabase local stack (app database — kb/brew/mem/nlq live here)
# =============================================================================
POSTGRES_PASSWORD={postgres_password}
JWT_SECRET={jwt_secret}
ANON_KEY={anon_key}
SERVICE_ROLE_KEY={service_key}
DASHBOARD_USERNAME=supabase
DASHBOARD_PASSWORD={dashboard_password}
# Newer Supabase key format (Studio display). Local stack uses the legacy
# ANON_KEY/SERVICE_ROLE_KEY above; leave these blank.
SUPABASE_PUBLISHABLE_KEY=
SUPABASE_SECRET_KEY=
SECRET_KEY_BASE={secrets.token_hex(32)}
VAULT_ENC_KEY={rand(32)}
PG_META_CRYPTO_KEY={rand(40)}

SUPABASE_PUBLIC_URL=http://localhost:8000
API_EXTERNAL_URL=http://localhost:8000
POSTGRES_HOST=db
POSTGRES_DB=postgres
POSTGRES_PORT=5432
POSTGRES_USER=postgres
POOLER_PROXY_PORT_TRANSACTION=6543
POOLER_DEFAULT_POOL_SIZE=20
POOLER_MAX_CLIENT_CONN=100
POOLER_TENANT_ID={rand(16)}
POOLER_DB_POOL_SIZE=5
KONG_HTTP_PORT=8000
KONG_HTTPS_PORT=8443
PGRST_DB_SCHEMAS=public,storage,graphql_public
SITE_URL=http://localhost:3000
ADDITIONAL_REDIRECT_URLS=
JWT_EXPIRY=3600
DISABLE_SIGNUP=false
MAILER_URLPATHS_CONFIRMATION="/auth/v1/verify"
MAILER_URLPATHS_INVITE="/auth/v1/verify"
MAILER_URLPATHS_RECOVERY="/auth/v1/verify"
MAILER_URLPATHS_EMAIL_CHANGE="/auth/v1/verify"
ENABLE_EMAIL_SIGNUP=true
ENABLE_EMAIL_AUTOCONFIRM=false
SMTP_ADMIN_EMAIL=admin@example.com
SMTP_HOST=supabase-mail
SMTP_PORT=2500
SMTP_USER=fake_mail_user
SMTP_PASS=fake_mail_password
SMTP_SENDER_NAME=fake_sender
ENABLE_ANONYMOUS_USERS=false
ENABLE_PHONE_SIGNUP=true
ENABLE_PHONE_AUTOCONFIRM=true
STUDIO_DEFAULT_ORGANIZATION=Homebrew Assistant
STUDIO_DEFAULT_PROJECT=Homebrew Assistant
OPENAI_API_KEY=
IMGPROXY_AUTO_WEBP=true
GLOBAL_S3_BUCKET=stub
REGION=stub
STORAGE_TENANT_ID=stub
S3_PROTOCOL_ACCESS_KEY_ID={secrets.token_hex(16)}
S3_PROTOCOL_ACCESS_KEY_SECRET={secrets.token_hex(32)}
FUNCTIONS_VERIFY_JWT=false
"""
    sys.stdout.write(env)


if __name__ == "__main__":
    main()
